package com.aicopilot.storage;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.DigestOutputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * {@link BlobStorage} on the local file system (MVP, KISS). On the server the directory is a Docker volume.
 * Writes go to a temporary file first and are moved into place atomically.
 */
@Component
class LocalDiskBlobStorage implements BlobStorage {

 private final Path root;

 LocalDiskBlobStorage(@Value("${copilot.storage.path}") String root) throws IOException {
  this.root = Path.of(root).toAbsolutePath().normalize();
  Files.createDirectories(this.root);
 }

 @Override
 public StoredBlob put(String key, InputStream content, long maxBytes) throws IOException {
  Path target = resolve(key);
  Files.createDirectories(target.getParent());
  Path temp = Files.createTempFile(target.getParent(), ".upload-", ".tmp");
  try {
   MessageDigest digest = sha256();
   long size = 0;
   byte[] buffer = new byte[64 * 1024];
   try (OutputStream out = new DigestOutputStream(Files.newOutputStream(temp), digest)) {
    int read;
    while ((read = content.read(buffer)) != -1) {
     size += read;
     if (size > maxBytes) {
      return new StoredBlob(size, null, true);
     }
     out.write(buffer, 0, read);
    }
   }
   Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
   return new StoredBlob(size, HexFormat.of().formatHex(digest.digest()), false);
  } finally {
   Files.deleteIfExists(temp);
  }
 }

 @Override
 public byte[] read(String key) throws IOException {
  return Files.readAllBytes(resolve(key));
 }

 @Override
 public void delete(String key) throws IOException {
  Files.deleteIfExists(resolve(key));
 }

 /** Keys are generated by the backend (userId/attachmentId); the check still blocks path traversal. */
 private Path resolve(String key) {
  Path path = root.resolve(key).normalize();
  if (!path.startsWith(root)) {
   throw new IllegalArgumentException("Invalid blob key");
  }
  return path;
 }

 private static MessageDigest sha256() {
  try {
   return MessageDigest.getInstance("SHA-256");
  } catch (NoSuchAlgorithmException e) {
   throw new IllegalStateException(e);
  }
 }
}
