// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
import HTTPTypes
/// Private backend for the AI Copilot iPhone and Apple Watch apps.
public struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    public init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// One-call snapshot for the Watch main screen.
    ///
    /// Returns the active conversation (created on first use), its current draft (created lazily), the latest AI request and the latest answer.
    ///
    ///
    /// - Remark: HTTP `GET /v1/home`.
    /// - Remark: Generated from `#/paths//v1/home/get(getHome)`.
    public func getHome(_ input: Operations.GetHome.Input) async throws -> Operations.GetHome.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetHome.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/home",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetHome.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.HomeSnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Conversations, most recently updated first.
    ///
    /// - Remark: HTTP `GET /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/get(listConversations)`.
    public func listConversations(_ input: Operations.ListConversations.Input) async throws -> Operations.ListConversations.Output {
        try await client.send(
            input: input,
            forOperation: Operations.ListConversations.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.ListConversations.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.Conversation].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Create an empty conversation and make it active on all devices.
    ///
    /// Idempotent by the client-generated id.
    ///
    /// - Remark: HTTP `POST /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/post(createConversation)`.
    public func createConversation(_ input: Operations.CreateConversation.Input) async throws -> Operations.CreateConversation.Output {
        try await client.send(
            input: input,
            forOperation: Operations.CreateConversation.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.CreateConversation.Output.Created.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Conversation.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .created(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Rename a conversation. A title set by the user is never replaced by an AI-suggested one.
    ///
    /// - Remark: HTTP `PATCH /v1/conversations/{conversationId}`.
    /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/patch(renameConversation)`.
    public func renameConversation(_ input: Operations.RenameConversation.Input) async throws -> Operations.RenameConversation.Output {
        try await client.send(
            input: input,
            forOperation: Operations.RenameConversation.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations/{}",
                    parameters: [
                        input.path.conversationId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .patch
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RenameConversation.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Conversation.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 400:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RenameConversation.Output.BadRequest.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .badRequest(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Delete a conversation with its messages, drafts and stored images (spec 47).
    ///
    /// Irreversible. Image bytes are deleted immediately. If it was the active conversation, the most recently updated remaining one becomes active (or a new one is created on the next home call). The AI cost report keeps the token counts, without any content. Idempotent: deleting a missing conversation returns 204.
    ///
    ///
    /// - Remark: HTTP `DELETE /v1/conversations/{conversationId}`.
    /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/delete(deleteConversation)`.
    public func deleteConversation(_ input: Operations.DeleteConversation.Input) async throws -> Operations.DeleteConversation.Output {
        try await client.send(
            input: input,
            forOperation: Operations.DeleteConversation.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations/{}",
                    parameters: [
                        input.path.conversationId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 204:
                    return .noContent(.init())
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Make a conversation active on all devices.
    ///
    /// - Remark: HTTP `PUT /v1/active-conversation`.
    /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)`.
    public func setActiveConversation(_ input: Operations.SetActiveConversation.Input) async throws -> Operations.SetActiveConversation.Output {
        try await client.send(
            input: input,
            forOperation: Operations.SetActiveConversation.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/active-conversation",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 204:
                    return .noContent(.init())
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Messages of a conversation in their stable order.
    ///
    /// - Remark: HTTP `GET /v1/conversations/{conversationId}/messages`.
    /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/messages/get(listMessages)`.
    public func listMessages(_ input: Operations.ListMessages.Input) async throws -> Operations.ListMessages.Output {
        try await client.send(
            input: input,
            forOperation: Operations.ListMessages.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations/{}/messages",
                    parameters: [
                        input.path.conversationId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.ListMessages.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.Message].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// The editable draft of a conversation with its attachments (created lazily).
    ///
    /// - Remark: HTTP `GET /v1/conversations/{conversationId}/draft`.
    /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/draft/get(getCurrentDraft)`.
    public func getCurrentDraft(_ input: Operations.GetCurrentDraft.Input) async throws -> Operations.GetCurrentDraft.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetCurrentDraft.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations/{}/draft",
                    parameters: [
                        input.path.conversationId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetCurrentDraft.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.DraftDetail.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Register an image in a draft before its bytes are uploaded.
    ///
    /// Step 1 of 2. The backend learns about the image before its bytes arrive, so a Send can wait for it and the Watch can show "Uploading 2/3". Idempotent by the client-generated attachment id. Position (order in the message) is assigned by the backend in registration order. Registering never starts AI inference.
    ///
    ///
    /// - Remark: HTTP `PUT /v1/drafts/{draftId}/attachments/{attachmentId}`.
    /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/attachments/{attachmentId}/put(registerAttachment)`.
    public func registerAttachment(_ input: Operations.RegisterAttachment.Input) async throws -> Operations.RegisterAttachment.Output {
        try await client.send(
            input: input,
            forOperation: Operations.RegisterAttachment.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/drafts/{}/attachments/{}",
                    parameters: [
                        input.path.draftId,
                        input.path.attachmentId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RegisterAttachment.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Attachment.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RegisterAttachment.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Remove an image from an editable draft.
    ///
    /// - Remark: HTTP `DELETE /v1/drafts/{draftId}/attachments/{attachmentId}`.
    /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/attachments/{attachmentId}/delete(removeAttachment)`.
    public func removeAttachment(_ input: Operations.RemoveAttachment.Input) async throws -> Operations.RemoveAttachment.Output {
        try await client.send(
            input: input,
            forOperation: Operations.RemoveAttachment.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/drafts/{}/attachments/{}",
                    parameters: [
                        input.path.draftId,
                        input.path.attachmentId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 204:
                    return .noContent(.init())
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RemoveAttachment.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Upload the bytes of a registered image (raw request body).
    ///
    /// Step 2 of 2. Raw body (not multipart), so iOS background URLSession can upload it from a file. Idempotent: repeating the upload of the same bytes is harmless. Allowed after Send while the draft waits for its images. Uploading never starts AI inference by itself; it may only complete a Send that is already waiting for this image.
    ///
    ///
    /// - Remark: HTTP `PUT /v1/attachments/{attachmentId}/content`.
    /// - Remark: Generated from `#/paths//v1/attachments/{attachmentId}/content/put(uploadAttachmentContent)`.
    public func uploadAttachmentContent(_ input: Operations.UploadAttachmentContent.Input) async throws -> Operations.UploadAttachmentContent.Output {
        try await client.send(
            input: input,
            forOperation: Operations.UploadAttachmentContent.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/attachments/{}/content",
                    parameters: [
                        input.path.attachmentId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .binary(value):
                    body = try converter.setRequiredRequestBodyAsBinary(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/octet-stream"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.UploadAttachmentContent.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Attachment.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.UploadAttachmentContent.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                case 422:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.UploadAttachmentContent.Output.UnprocessableContent.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unprocessableContent(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Explicit Send - the only operation that starts AI inference.
    ///
    /// Freezes the draft and creates an AI request. Idempotent by `Idempotency-Key`: repeating the call with the same key returns the same request. A second submit of the same draft with a different key returns 409 (e.g. Watch and iPhone pressed Send at the same time).
    ///
    ///
    /// - Remark: HTTP `POST /v1/drafts/{draftId}/submit`.
    /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)`.
    public func submitDraft(_ input: Operations.SubmitDraft.Input) async throws -> Operations.SubmitDraft.Output {
        try await client.send(
            input: input,
            forOperation: Operations.SubmitDraft.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/drafts/{}/submit",
                    parameters: [
                        input.path.draftId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Idempotency-Key",
                    value: input.headers.idempotencyKey
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 202:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.SubmitDraft.Output.Accepted.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AiRequest.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .accepted(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.SubmitDraft.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                case 422:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.SubmitDraft.Output.UnprocessableContent.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unprocessableContent(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Cancel a Send that still waits for its images; the photos and text return to the draft.
    ///
    /// Allowed while the request is waitingForAttachments or blocked (no message exists yet, spec 26). Idempotent: cancelling a cancelled request returns it unchanged.
    ///
    ///
    /// - Remark: HTTP `POST /v1/requests/{requestId}/cancel`.
    /// - Remark: Generated from `#/paths//v1/requests/{requestId}/cancel/post(cancelRequest)`.
    public func cancelRequest(_ input: Operations.CancelRequest.Input) async throws -> Operations.CancelRequest.Output {
        try await client.send(
            input: input,
            forOperation: Operations.CancelRequest.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/requests/{}/cancel",
                    parameters: [
                        input.path.requestId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.CancelRequest.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AiRequest.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.CancelRequest.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Ask the AI again after a failed answer. Reuses the same question; no new message is created.
    ///
    /// Allowed for a failed request whose question is still the last message of its conversation. Idempotent: retrying a request that is already queued, processing or completed returns it unchanged.
    ///
    ///
    /// - Remark: HTTP `POST /v1/requests/{requestId}/retry`.
    /// - Remark: Generated from `#/paths//v1/requests/{requestId}/retry/post(retryRequest)`.
    public func retryRequest(_ input: Operations.RetryRequest.Input) async throws -> Operations.RetryRequest.Output {
        try await client.send(
            input: input,
            forOperation: Operations.RetryRequest.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/requests/{}/retry",
                    parameters: [
                        input.path.requestId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 202:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RetryRequest.Output.Accepted.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AiRequest.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .accepted(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.RetryRequest.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// State of an AI request, optionally long-polling for a change.
    ///
    /// - Remark: HTTP `GET /v1/requests/{requestId}`.
    /// - Remark: Generated from `#/paths//v1/requests/{requestId}/get(getRequest)`.
    public func getRequest(_ input: Operations.GetRequest.Input) async throws -> Operations.GetRequest.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetRequest.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/requests/{}",
                    parameters: [
                        input.path.requestId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "waitSeconds",
                    value: input.query.waitSeconds
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetRequest.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AiRequest.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// AI token usage and its estimated cost for today, this month and all time.
    ///
    /// Cost is estimated from token counts with the prices configured on the backend (USD per 1M tokens). "Today" and "this month" use the backend's reporting time zone.
    ///
    ///
    /// - Remark: HTTP `GET /v1/usage`.
    /// - Remark: Generated from `#/paths//v1/usage/get(getUsage)`.
    public func getUsage(_ input: Operations.GetUsage.Input) async throws -> Operations.GetUsage.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetUsage.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/usage",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetUsage.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UsageReport.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
}
