// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
import HTTPTypes
/// Private backend for the AI Copilot iPhone and Apple Watch apps.
public struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    public init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// One-call snapshot for the Watch main screen.
    ///
    /// Returns the active conversation (created on first use), its current draft (created lazily), the latest AI request and the latest answer.
    ///
    ///
    /// - Remark: HTTP `GET /v1/home`.
    /// - Remark: Generated from `#/paths//v1/home/get(getHome)`.
    public func getHome(_ input: Operations.GetHome.Input) async throws -> Operations.GetHome.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetHome.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/home",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetHome.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.HomeSnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Conversations, most recently updated first.
    ///
    /// - Remark: HTTP `GET /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/get(listConversations)`.
    public func listConversations(_ input: Operations.ListConversations.Input) async throws -> Operations.ListConversations.Output {
        try await client.send(
            input: input,
            forOperation: Operations.ListConversations.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.ListConversations.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.Conversation].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Create an empty conversation and make it active on all devices.
    ///
    /// Idempotent by the client-generated id.
    ///
    /// - Remark: HTTP `POST /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/post(createConversation)`.
    public func createConversation(_ input: Operations.CreateConversation.Input) async throws -> Operations.CreateConversation.Output {
        try await client.send(
            input: input,
            forOperation: Operations.CreateConversation.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.CreateConversation.Output.Created.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Conversation.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .created(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Make a conversation active on all devices.
    ///
    /// - Remark: HTTP `PUT /v1/active-conversation`.
    /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)`.
    public func setActiveConversation(_ input: Operations.SetActiveConversation.Input) async throws -> Operations.SetActiveConversation.Output {
        try await client.send(
            input: input,
            forOperation: Operations.SetActiveConversation.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/active-conversation",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 204:
                    return .noContent(.init())
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Messages of a conversation in their stable order.
    ///
    /// - Remark: HTTP `GET /v1/conversations/{conversationId}/messages`.
    /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/messages/get(listMessages)`.
    public func listMessages(_ input: Operations.ListMessages.Input) async throws -> Operations.ListMessages.Output {
        try await client.send(
            input: input,
            forOperation: Operations.ListMessages.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/conversations/{}/messages",
                    parameters: [
                        input.path.conversationId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.ListMessages.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.Message].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Explicit Send - the only operation that starts AI inference.
    ///
    /// Freezes the draft and creates an AI request. Idempotent by `Idempotency-Key`: repeating the call with the same key returns the same request. A second submit of the same draft with a different key returns 409 (e.g. Watch and iPhone pressed Send at the same time).
    ///
    ///
    /// - Remark: HTTP `POST /v1/drafts/{draftId}/submit`.
    /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)`.
    public func submitDraft(_ input: Operations.SubmitDraft.Input) async throws -> Operations.SubmitDraft.Output {
        try await client.send(
            input: input,
            forOperation: Operations.SubmitDraft.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/drafts/{}/submit",
                    parameters: [
                        input.path.draftId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                try converter.setHeaderFieldAsURI(
                    in: &request.headerFields,
                    name: "Idempotency-Key",
                    value: input.headers.idempotencyKey
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 202:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.SubmitDraft.Output.Accepted.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AiRequest.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .accepted(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.SubmitDraft.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                case 422:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.SubmitDraft.Output.UnprocessableContent.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unprocessableContent(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// State of an AI request, optionally long-polling for a change.
    ///
    /// - Remark: HTTP `GET /v1/requests/{requestId}`.
    /// - Remark: Generated from `#/paths//v1/requests/{requestId}/get(getRequest)`.
    public func getRequest(_ input: Operations.GetRequest.Input) async throws -> Operations.GetRequest.Output {
        try await client.send(
            input: input,
            forOperation: Operations.GetRequest.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1/requests/{}",
                    parameters: [
                        input.path.requestId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "waitSeconds",
                    value: input.query.waitSeconds
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.GetRequest.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AiRequest.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 401:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.Unauthorized.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unauthorized(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/problem+json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/problem+json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Problem.self,
                            from: responseBody,
                            transforming: { value in
                                .applicationProblemJson(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
}
