// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// One-call snapshot for the Watch main screen.
    ///
    /// Returns the active conversation (created on first use), its current draft (created lazily), the latest AI request and the latest answer.
    ///
    ///
    /// - Remark: HTTP `GET /v1/home`.
    /// - Remark: Generated from `#/paths//v1/home/get(getHome)`.
    func getHome(_ input: Operations.GetHome.Input) async throws -> Operations.GetHome.Output
    /// Conversations, most recently updated first.
    ///
    /// - Remark: HTTP `GET /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/get(listConversations)`.
    func listConversations(_ input: Operations.ListConversations.Input) async throws -> Operations.ListConversations.Output
    /// Create an empty conversation and make it active on all devices.
    ///
    /// Idempotent by the client-generated id.
    ///
    /// - Remark: HTTP `POST /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/post(createConversation)`.
    func createConversation(_ input: Operations.CreateConversation.Input) async throws -> Operations.CreateConversation.Output
    /// Make a conversation active on all devices.
    ///
    /// - Remark: HTTP `PUT /v1/active-conversation`.
    /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)`.
    func setActiveConversation(_ input: Operations.SetActiveConversation.Input) async throws -> Operations.SetActiveConversation.Output
    /// Messages of a conversation in their stable order.
    ///
    /// - Remark: HTTP `GET /v1/conversations/{conversationId}/messages`.
    /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/messages/get(listMessages)`.
    func listMessages(_ input: Operations.ListMessages.Input) async throws -> Operations.ListMessages.Output
    /// Explicit Send - the only operation that starts AI inference.
    ///
    /// Freezes the draft and creates an AI request. Idempotent by `Idempotency-Key`: repeating the call with the same key returns the same request. A second submit of the same draft with a different key returns 409 (e.g. Watch and iPhone pressed Send at the same time).
    ///
    ///
    /// - Remark: HTTP `POST /v1/drafts/{draftId}/submit`.
    /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)`.
    func submitDraft(_ input: Operations.SubmitDraft.Input) async throws -> Operations.SubmitDraft.Output
    /// State of an AI request, optionally long-polling for a change.
    ///
    /// - Remark: HTTP `GET /v1/requests/{requestId}`.
    /// - Remark: Generated from `#/paths//v1/requests/{requestId}/get(getRequest)`.
    func getRequest(_ input: Operations.GetRequest.Input) async throws -> Operations.GetRequest.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// One-call snapshot for the Watch main screen.
    ///
    /// Returns the active conversation (created on first use), its current draft (created lazily), the latest AI request and the latest answer.
    ///
    ///
    /// - Remark: HTTP `GET /v1/home`.
    /// - Remark: Generated from `#/paths//v1/home/get(getHome)`.
    public func getHome(headers: Operations.GetHome.Input.Headers = .init()) async throws -> Operations.GetHome.Output {
        try await getHome(Operations.GetHome.Input(headers: headers))
    }
    /// Conversations, most recently updated first.
    ///
    /// - Remark: HTTP `GET /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/get(listConversations)`.
    public func listConversations(headers: Operations.ListConversations.Input.Headers = .init()) async throws -> Operations.ListConversations.Output {
        try await listConversations(Operations.ListConversations.Input(headers: headers))
    }
    /// Create an empty conversation and make it active on all devices.
    ///
    /// Idempotent by the client-generated id.
    ///
    /// - Remark: HTTP `POST /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/post(createConversation)`.
    public func createConversation(
        headers: Operations.CreateConversation.Input.Headers = .init(),
        body: Operations.CreateConversation.Input.Body
    ) async throws -> Operations.CreateConversation.Output {
        try await createConversation(Operations.CreateConversation.Input(
            headers: headers,
            body: body
        ))
    }
    /// Make a conversation active on all devices.
    ///
    /// - Remark: HTTP `PUT /v1/active-conversation`.
    /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)`.
    public func setActiveConversation(
        headers: Operations.SetActiveConversation.Input.Headers = .init(),
        body: Operations.SetActiveConversation.Input.Body
    ) async throws -> Operations.SetActiveConversation.Output {
        try await setActiveConversation(Operations.SetActiveConversation.Input(
            headers: headers,
            body: body
        ))
    }
    /// Messages of a conversation in their stable order.
    ///
    /// - Remark: HTTP `GET /v1/conversations/{conversationId}/messages`.
    /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/messages/get(listMessages)`.
    public func listMessages(
        path: Operations.ListMessages.Input.Path,
        headers: Operations.ListMessages.Input.Headers = .init()
    ) async throws -> Operations.ListMessages.Output {
        try await listMessages(Operations.ListMessages.Input(
            path: path,
            headers: headers
        ))
    }
    /// Explicit Send - the only operation that starts AI inference.
    ///
    /// Freezes the draft and creates an AI request. Idempotent by `Idempotency-Key`: repeating the call with the same key returns the same request. A second submit of the same draft with a different key returns 409 (e.g. Watch and iPhone pressed Send at the same time).
    ///
    ///
    /// - Remark: HTTP `POST /v1/drafts/{draftId}/submit`.
    /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)`.
    public func submitDraft(
        path: Operations.SubmitDraft.Input.Path,
        headers: Operations.SubmitDraft.Input.Headers,
        body: Operations.SubmitDraft.Input.Body
    ) async throws -> Operations.SubmitDraft.Output {
        try await submitDraft(Operations.SubmitDraft.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// State of an AI request, optionally long-polling for a change.
    ///
    /// - Remark: HTTP `GET /v1/requests/{requestId}`.
    /// - Remark: Generated from `#/paths//v1/requests/{requestId}/get(getRequest)`.
    public func getRequest(
        path: Operations.GetRequest.Input.Path,
        query: Operations.GetRequest.Input.Query = .init(),
        headers: Operations.GetRequest.Input.Headers = .init()
    ) async throws -> Operations.GetRequest.Output {
        try await getRequest(Operations.GetRequest.Input(
            path: path,
            query: query,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "/",
            variables: []
        )
    }
}
