// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {
        public struct Unauthorized: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/Unauthorized/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/Unauthorized/content/application\/problem+json`.
                case applicationProblemJson(Components.Schemas.Problem)
                /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                ///
                /// - Throws: An error if `self` is not `.applicationProblemJson`.
                /// - SeeAlso: `.applicationProblemJson`.
                public var applicationProblemJson: Components.Schemas.Problem {
                    get throws {
                        switch self {
                        case let .applicationProblemJson(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.Unauthorized.Body
            /// Creates a new `Unauthorized`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.Unauthorized.Body) {
                self.body = body
            }
        }
        public struct NotFound: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NotFound/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NotFound/content/application\/problem+json`.
                case applicationProblemJson(Components.Schemas.Problem)
                /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                ///
                /// - Throws: An error if `self` is not `.applicationProblemJson`.
                /// - SeeAlso: `.applicationProblemJson`.
                public var applicationProblemJson: Components.Schemas.Problem {
                    get throws {
                        switch self {
                        case let .applicationProblemJson(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NotFound.Body
            /// Creates a new `NotFound`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NotFound.Body) {
                self.body = body
            }
        }
    }
}
