// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// One-call snapshot for the Watch main screen.
    ///
    /// Returns the active conversation (created on first use), its current draft (created lazily), the latest AI request and the latest answer.
    ///
    ///
    /// - Remark: HTTP `GET /v1/home`.
    /// - Remark: Generated from `#/paths//v1/home/get(getHome)`.
    public enum GetHome {
        public static let id: Swift.String = "getHome"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/home/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetHome.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetHome.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.GetHome.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.GetHome.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/home/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/home/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.HomeSnapshot)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HomeSnapshot {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.GetHome.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.GetHome.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Snapshot.
            ///
            /// - Remark: Generated from `#/paths//v1/home/get(getHome)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.GetHome.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.GetHome.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid device token.
            ///
            /// - Remark: Generated from `#/paths//v1/home/get(getHome)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case applicationProblemJson
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                case "application/problem+json":
                    self = .applicationProblemJson
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                case .applicationProblemJson:
                    return "application/problem+json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json,
                    .applicationProblemJson
                ]
            }
        }
    }
    /// Conversations, most recently updated first.
    ///
    /// - Remark: HTTP `GET /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/get(listConversations)`.
    public enum ListConversations {
        public static let id: Swift.String = "listConversations"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/conversations/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ListConversations.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ListConversations.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.ListConversations.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.ListConversations.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/conversations/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/conversations/GET/responses/200/content/application\/json`.
                    case json([Components.Schemas.Conversation])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: [Components.Schemas.Conversation] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.ListConversations.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.ListConversations.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Conversations.
            ///
            /// - Remark: Generated from `#/paths//v1/conversations/get(listConversations)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.ListConversations.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.ListConversations.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid device token.
            ///
            /// - Remark: Generated from `#/paths//v1/conversations/get(listConversations)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case applicationProblemJson
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                case "application/problem+json":
                    self = .applicationProblemJson
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                case .applicationProblemJson:
                    return "application/problem+json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json,
                    .applicationProblemJson
                ]
            }
        }
    }
    /// Create an empty conversation and make it active on all devices.
    ///
    /// Idempotent by the client-generated id.
    ///
    /// - Remark: HTTP `POST /v1/conversations`.
    /// - Remark: Generated from `#/paths//v1/conversations/post(createConversation)`.
    public enum CreateConversation {
        public static let id: Swift.String = "createConversation"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/conversations/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.CreateConversation.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.CreateConversation.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.CreateConversation.Input.Headers
            /// - Remark: Generated from `#/paths/v1/conversations/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/conversations/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.CreateConversationRequest)
            }
            public var body: Operations.CreateConversation.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.CreateConversation.Input.Headers = .init(),
                body: Operations.CreateConversation.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Created: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/conversations/POST/responses/201/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/conversations/POST/responses/201/content/application\/json`.
                    case json(Components.Schemas.Conversation)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.Conversation {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.CreateConversation.Output.Created.Body
                /// Creates a new `Created`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.CreateConversation.Output.Created.Body) {
                    self.body = body
                }
            }
            /// Created (or already existed with this id).
            ///
            /// - Remark: Generated from `#/paths//v1/conversations/post(createConversation)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.CreateConversation.Output.Created)
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            public var created: Operations.CreateConversation.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid device token.
            ///
            /// - Remark: Generated from `#/paths//v1/conversations/post(createConversation)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case applicationProblemJson
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                case "application/problem+json":
                    self = .applicationProblemJson
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                case .applicationProblemJson:
                    return "application/problem+json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json,
                    .applicationProblemJson
                ]
            }
        }
    }
    /// Make a conversation active on all devices.
    ///
    /// - Remark: HTTP `PUT /v1/active-conversation`.
    /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)`.
    public enum SetActiveConversation {
        public static let id: Swift.String = "setActiveConversation"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/active-conversation/PUT/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.SetActiveConversation.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.SetActiveConversation.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.SetActiveConversation.Input.Headers
            /// - Remark: Generated from `#/paths/v1/active-conversation/PUT/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/active-conversation/PUT/requestBody/content/application\/json`.
                case json(Components.Schemas.SetActiveConversationRequest)
            }
            public var body: Operations.SetActiveConversation.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.SetActiveConversation.Input.Headers = .init(),
                body: Operations.SetActiveConversation.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct NoContent: Sendable, Hashable {
                /// Creates a new `NoContent`.
                public init() {}
            }
            /// Done.
            ///
            /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            case noContent(Operations.SetActiveConversation.Output.NoContent)
            /// Done.
            ///
            /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            public static var noContent: Self {
                .noContent(.init())
            }
            /// The associated value of the enum case if `self` is `.noContent`.
            ///
            /// - Throws: An error if `self` is not `.noContent`.
            /// - SeeAlso: `.noContent`.
            public var noContent: Operations.SetActiveConversation.Output.NoContent {
                get throws {
                    switch self {
                    case let .noContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "noContent",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid device token.
            ///
            /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Not found (or belongs to another user).
            ///
            /// - Remark: Generated from `#/paths//v1/active-conversation/put(setActiveConversation)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Components.Responses.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            public var notFound: Components.Responses.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case applicationProblemJson
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/problem+json":
                    self = .applicationProblemJson
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .applicationProblemJson:
                    return "application/problem+json"
                }
            }
            public static var allCases: [Self] {
                [
                    .applicationProblemJson
                ]
            }
        }
    }
    /// Messages of a conversation in their stable order.
    ///
    /// - Remark: HTTP `GET /v1/conversations/{conversationId}/messages`.
    /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/messages/get(listMessages)`.
    public enum ListMessages {
        public static let id: Swift.String = "listMessages"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/conversations/{conversationId}/messages/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/conversations/{conversationId}/messages/GET/path/conversationId`.
                public var conversationId: Components.Parameters.ConversationId
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - conversationId:
                public init(conversationId: Components.Parameters.ConversationId) {
                    self.conversationId = conversationId
                }
            }
            public var path: Operations.ListMessages.Input.Path
            /// - Remark: Generated from `#/paths/v1/conversations/{conversationId}/messages/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ListMessages.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ListMessages.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.ListMessages.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.ListMessages.Input.Path,
                headers: Operations.ListMessages.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/conversations/{conversationId}/messages/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/conversations/{conversationId}/messages/GET/responses/200/content/application\/json`.
                    case json([Components.Schemas.Message])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: [Components.Schemas.Message] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.ListMessages.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.ListMessages.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Messages.
            ///
            /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/messages/get(listMessages)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.ListMessages.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.ListMessages.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid device token.
            ///
            /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/messages/get(listMessages)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Not found (or belongs to another user).
            ///
            /// - Remark: Generated from `#/paths//v1/conversations/{conversationId}/messages/get(listMessages)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Components.Responses.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            public var notFound: Components.Responses.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case applicationProblemJson
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                case "application/problem+json":
                    self = .applicationProblemJson
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                case .applicationProblemJson:
                    return "application/problem+json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json,
                    .applicationProblemJson
                ]
            }
        }
    }
    /// Explicit Send - the only operation that starts AI inference.
    ///
    /// Freezes the draft and creates an AI request. Idempotent by `Idempotency-Key`: repeating the call with the same key returns the same request. A second submit of the same draft with a different key returns 409 (e.g. Watch and iPhone pressed Send at the same time).
    ///
    ///
    /// - Remark: HTTP `POST /v1/drafts/{draftId}/submit`.
    /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)`.
    public enum SubmitDraft {
        public static let id: Swift.String = "submitDraft"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/path/draftId`.
                public var draftId: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - draftId:
                public init(draftId: Swift.String) {
                    self.draftId = draftId
                }
            }
            public var path: Operations.SubmitDraft.Input.Path
            /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/header`.
            public struct Headers: Sendable, Hashable {
                /// Generated by the client once per user action.
                ///
                /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/header/Idempotency-Key`.
                public var idempotencyKey: Swift.String
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.SubmitDraft.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - idempotencyKey: Generated by the client once per user action.
                ///   - accept:
                public init(
                    idempotencyKey: Swift.String,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.SubmitDraft.AcceptableContentType>] = .defaultValues()
                ) {
                    self.idempotencyKey = idempotencyKey
                    self.accept = accept
                }
            }
            public var headers: Operations.SubmitDraft.Input.Headers
            /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.SubmitDraftRequest)
            }
            public var body: Operations.SubmitDraft.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            public init(
                path: Operations.SubmitDraft.Input.Path,
                headers: Operations.SubmitDraft.Input.Headers,
                body: Operations.SubmitDraft.Input.Body
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Accepted: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/responses/202/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/responses/202/content/application\/json`.
                    case json(Components.Schemas.AiRequest)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.AiRequest {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.SubmitDraft.Output.Accepted.Body
                /// Creates a new `Accepted`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.SubmitDraft.Output.Accepted.Body) {
                    self.body = body
                }
            }
            /// Accepted; processing continues on the backend.
            ///
            /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)/responses/202`.
            ///
            /// HTTP response code: `202 accepted`.
            case accepted(Operations.SubmitDraft.Output.Accepted)
            /// The associated value of the enum case if `self` is `.accepted`.
            ///
            /// - Throws: An error if `self` is not `.accepted`.
            /// - SeeAlso: `.accepted`.
            public var accepted: Operations.SubmitDraft.Output.Accepted {
                get throws {
                    switch self {
                    case let .accepted(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "accepted",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid device token.
            ///
            /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Not found (or belongs to another user).
            ///
            /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Components.Responses.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            public var notFound: Components.Responses.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            public struct Conflict: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/responses/409/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/responses/409/content/application\/problem+json`.
                    case applicationProblemJson(Components.Schemas.Problem)
                    /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                    ///
                    /// - Throws: An error if `self` is not `.applicationProblemJson`.
                    /// - SeeAlso: `.applicationProblemJson`.
                    public var applicationProblemJson: Components.Schemas.Problem {
                        get throws {
                            switch self {
                            case let .applicationProblemJson(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.SubmitDraft.Output.Conflict.Body
                /// Creates a new `Conflict`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.SubmitDraft.Output.Conflict.Body) {
                    self.body = body
                }
            }
            /// The draft was already submitted with another idempotency key.
            ///
            /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)/responses/409`.
            ///
            /// HTTP response code: `409 conflict`.
            case conflict(Operations.SubmitDraft.Output.Conflict)
            /// The associated value of the enum case if `self` is `.conflict`.
            ///
            /// - Throws: An error if `self` is not `.conflict`.
            /// - SeeAlso: `.conflict`.
            public var conflict: Operations.SubmitDraft.Output.Conflict {
                get throws {
                    switch self {
                    case let .conflict(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "conflict",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/drafts/{draftId}/submit/POST/responses/422/content/application\/problem+json`.
                    case applicationProblemJson(Components.Schemas.Problem)
                    /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                    ///
                    /// - Throws: An error if `self` is not `.applicationProblemJson`.
                    /// - SeeAlso: `.applicationProblemJson`.
                    public var applicationProblemJson: Components.Schemas.Problem {
                        get throws {
                            switch self {
                            case let .applicationProblemJson(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.SubmitDraft.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.SubmitDraft.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// The draft has neither text nor attachments.
            ///
            /// - Remark: Generated from `#/paths//v1/drafts/{draftId}/submit/post(submitDraft)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.SubmitDraft.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.SubmitDraft.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case applicationProblemJson
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                case "application/problem+json":
                    self = .applicationProblemJson
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                case .applicationProblemJson:
                    return "application/problem+json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json,
                    .applicationProblemJson
                ]
            }
        }
    }
    /// State of an AI request, optionally long-polling for a change.
    ///
    /// - Remark: HTTP `GET /v1/requests/{requestId}`.
    /// - Remark: Generated from `#/paths//v1/requests/{requestId}/get(getRequest)`.
    public enum GetRequest {
        public static let id: Swift.String = "getRequest"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/requests/{requestId}/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/requests/{requestId}/GET/path/requestId`.
                public var requestId: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - requestId:
                public init(requestId: Swift.String) {
                    self.requestId = requestId
                }
            }
            public var path: Operations.GetRequest.Input.Path
            /// - Remark: Generated from `#/paths/v1/requests/{requestId}/GET/query`.
            public struct Query: Sendable, Hashable {
                /// 0 = return immediately. Otherwise wait up to this many seconds until the state differs from its state at the time of the call, or the request reaches a terminal state.
                ///
                ///
                /// - Remark: Generated from `#/paths/v1/requests/{requestId}/GET/query/waitSeconds`.
                public var waitSeconds: Swift.Int?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - waitSeconds: 0 = return immediately. Otherwise wait up to this many seconds until the state differs from its state at the time of the call, or the request reaches a terminal state.
                public init(waitSeconds: Swift.Int? = nil) {
                    self.waitSeconds = waitSeconds
                }
            }
            public var query: Operations.GetRequest.Input.Query
            /// - Remark: Generated from `#/paths/v1/requests/{requestId}/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetRequest.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetRequest.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.GetRequest.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - query:
            ///   - headers:
            public init(
                path: Operations.GetRequest.Input.Path,
                query: Operations.GetRequest.Input.Query = .init(),
                headers: Operations.GetRequest.Input.Headers = .init()
            ) {
                self.path = path
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/requests/{requestId}/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/requests/{requestId}/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.AiRequest)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.AiRequest {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.GetRequest.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.GetRequest.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Current state.
            ///
            /// - Remark: Generated from `#/paths//v1/requests/{requestId}/get(getRequest)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.GetRequest.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.GetRequest.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid device token.
            ///
            /// - Remark: Generated from `#/paths//v1/requests/{requestId}/get(getRequest)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Not found (or belongs to another user).
            ///
            /// - Remark: Generated from `#/paths//v1/requests/{requestId}/get(getRequest)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Components.Responses.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            public var notFound: Components.Responses.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case applicationProblemJson
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                case "application/problem+json":
                    self = .applicationProblemJson
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                case .applicationProblemJson:
                    return "application/problem+json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json,
                    .applicationProblemJson
                ]
            }
        }
    }
}
