// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/HomeSnapshot`.
        public struct HomeSnapshot: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/HomeSnapshot/activeConversation`.
            public var activeConversation: Components.Schemas.Conversation
            /// - Remark: Generated from `#/components/schemas/HomeSnapshot/draft`.
            public var draft: Components.Schemas.DraftSummary
            /// - Remark: Generated from `#/components/schemas/HomeSnapshot/latestRequest`.
            public var latestRequest: Components.Schemas.AiRequest?
            /// - Remark: Generated from `#/components/schemas/HomeSnapshot/lastAnswer`.
            public var lastAnswer: Components.Schemas.Message?
            /// Creates a new `HomeSnapshot`.
            ///
            /// - Parameters:
            ///   - activeConversation:
            ///   - draft:
            ///   - latestRequest:
            ///   - lastAnswer:
            public init(
                activeConversation: Components.Schemas.Conversation,
                draft: Components.Schemas.DraftSummary,
                latestRequest: Components.Schemas.AiRequest? = nil,
                lastAnswer: Components.Schemas.Message? = nil
            ) {
                self.activeConversation = activeConversation
                self.draft = draft
                self.latestRequest = latestRequest
                self.lastAnswer = lastAnswer
            }
            public enum CodingKeys: String, CodingKey {
                case activeConversation
                case draft
                case latestRequest
                case lastAnswer
            }
        }
        /// - Remark: Generated from `#/components/schemas/Conversation`.
        public struct Conversation: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Conversation/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/Conversation/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/Conversation/mode`.
            public var mode: Components.Schemas.ConversationMode
            /// - Remark: Generated from `#/components/schemas/Conversation/updatedAt`.
            public var updatedAt: Foundation.Date
            /// Creates a new `Conversation`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - mode:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                title: Swift.String,
                mode: Components.Schemas.ConversationMode,
                updatedAt: Foundation.Date
            ) {
                self.id = id
                self.title = title
                self.mode = mode
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case mode
                case updatedAt
            }
        }
        /// What the conversation is for, chosen at creation. danishExam adds the DU3 exam guide and the official study materials to the AI's instructions.
        ///
        ///
        /// - Remark: Generated from `#/components/schemas/ConversationMode`.
        @frozen public enum ConversationMode: String, Codable, Hashable, Sendable, CaseIterable {
            case general = "general"
            case danishExam = "danishExam"
        }
        /// - Remark: Generated from `#/components/schemas/CreateConversationRequest`.
        public struct CreateConversationRequest: Codable, Hashable, Sendable {
            /// Client-generated id; makes the call idempotent.
            ///
            /// - Remark: Generated from `#/components/schemas/CreateConversationRequest/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/CreateConversationRequest/mode`.
            public var mode: Components.Schemas.ConversationMode?
            /// Creates a new `CreateConversationRequest`.
            ///
            /// - Parameters:
            ///   - id: Client-generated id; makes the call idempotent.
            ///   - mode:
            public init(
                id: Swift.String,
                mode: Components.Schemas.ConversationMode? = nil
            ) {
                self.id = id
                self.mode = mode
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case mode
            }
        }
        /// - Remark: Generated from `#/components/schemas/SetActiveConversationRequest`.
        public struct SetActiveConversationRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SetActiveConversationRequest/conversationId`.
            public var conversationId: Swift.String
            /// Creates a new `SetActiveConversationRequest`.
            ///
            /// - Parameters:
            ///   - conversationId:
            public init(conversationId: Swift.String) {
                self.conversationId = conversationId
            }
            public enum CodingKeys: String, CodingKey {
                case conversationId
            }
        }
        /// - Remark: Generated from `#/components/schemas/Message`.
        public struct Message: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Message/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/Message/conversationId`.
            public var conversationId: Swift.String
            /// - Remark: Generated from `#/components/schemas/Message/role`.
            @frozen public enum RolePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case user = "user"
                case assistant = "assistant"
            }
            /// - Remark: Generated from `#/components/schemas/Message/role`.
            public var role: Components.Schemas.Message.RolePayload
            /// Null for image-only user messages.
            ///
            /// - Remark: Generated from `#/components/schemas/Message/text`.
            public var text: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Message/attachmentCount`.
            public var attachmentCount: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Message/suggestedActions`.
            public var suggestedActions: [Components.Schemas.SuggestedAction]
            /// - Remark: Generated from `#/components/schemas/Message/createdAt`.
            public var createdAt: Foundation.Date
            /// Creates a new `Message`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - conversationId:
            ///   - role:
            ///   - text: Null for image-only user messages.
            ///   - attachmentCount:
            ///   - suggestedActions:
            ///   - createdAt:
            public init(
                id: Swift.String,
                conversationId: Swift.String,
                role: Components.Schemas.Message.RolePayload,
                text: Swift.String? = nil,
                attachmentCount: Swift.Int,
                suggestedActions: [Components.Schemas.SuggestedAction],
                createdAt: Foundation.Date
            ) {
                self.id = id
                self.conversationId = conversationId
                self.role = role
                self.text = text
                self.attachmentCount = attachmentCount
                self.suggestedActions = suggestedActions
                self.createdAt = createdAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case conversationId
                case role
                case text
                case attachmentCount
                case suggestedActions
                case createdAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/SuggestedAction`.
        public struct SuggestedAction: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SuggestedAction/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/SuggestedAction/prompt`.
            public var prompt: Swift.String
            /// Creates a new `SuggestedAction`.
            ///
            /// - Parameters:
            ///   - title:
            ///   - prompt:
            public init(
                title: Swift.String,
                prompt: Swift.String
            ) {
                self.title = title
                self.prompt = prompt
            }
            public enum CodingKeys: String, CodingKey {
                case title
                case prompt
            }
        }
        /// - Remark: Generated from `#/components/schemas/DraftSummary`.
        public struct DraftSummary: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DraftSummary/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/DraftSummary/text`.
            public var text: Swift.String?
            /// - Remark: Generated from `#/components/schemas/DraftSummary/totalAttachments`.
            public var totalAttachments: Swift.Int
            /// - Remark: Generated from `#/components/schemas/DraftSummary/uploadedAttachments`.
            public var uploadedAttachments: Swift.Int
            /// - Remark: Generated from `#/components/schemas/DraftSummary/failedAttachments`.
            public var failedAttachments: Swift.Int
            /// Creates a new `DraftSummary`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - text:
            ///   - totalAttachments:
            ///   - uploadedAttachments:
            ///   - failedAttachments:
            public init(
                id: Swift.String,
                text: Swift.String? = nil,
                totalAttachments: Swift.Int,
                uploadedAttachments: Swift.Int,
                failedAttachments: Swift.Int
            ) {
                self.id = id
                self.text = text
                self.totalAttachments = totalAttachments
                self.uploadedAttachments = uploadedAttachments
                self.failedAttachments = failedAttachments
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case text
                case totalAttachments
                case uploadedAttachments
                case failedAttachments
            }
        }
        /// - Remark: Generated from `#/components/schemas/DraftDetail`.
        public struct DraftDetail: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DraftDetail/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/DraftDetail/conversationId`.
            public var conversationId: Swift.String
            /// - Remark: Generated from `#/components/schemas/DraftDetail/text`.
            public var text: Swift.String?
            /// - Remark: Generated from `#/components/schemas/DraftDetail/state`.
            @frozen public enum StatePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case open = "open"
                case frozen = "frozen"
                case consumed = "consumed"
            }
            /// - Remark: Generated from `#/components/schemas/DraftDetail/state`.
            public var state: Components.Schemas.DraftDetail.StatePayload
            /// In message order.
            ///
            /// - Remark: Generated from `#/components/schemas/DraftDetail/attachments`.
            public var attachments: [Components.Schemas.Attachment]
            /// Creates a new `DraftDetail`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - conversationId:
            ///   - text:
            ///   - state:
            ///   - attachments: In message order.
            public init(
                id: Swift.String,
                conversationId: Swift.String,
                text: Swift.String? = nil,
                state: Components.Schemas.DraftDetail.StatePayload,
                attachments: [Components.Schemas.Attachment]
            ) {
                self.id = id
                self.conversationId = conversationId
                self.text = text
                self.state = state
                self.attachments = attachments
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case conversationId
                case text
                case state
                case attachments
            }
        }
        /// - Remark: Generated from `#/components/schemas/Attachment`.
        public struct Attachment: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Attachment/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/Attachment/draftId`.
            public var draftId: Swift.String
            /// - Remark: Generated from `#/components/schemas/Attachment/position`.
            public var position: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Attachment/source`.
            public var source: Components.Schemas.AttachmentSource
            /// - Remark: Generated from `#/components/schemas/Attachment/state`.
            @frozen public enum StatePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case pending = "pending"
                case uploaded = "uploaded"
                case failed = "failed"
            }
            /// - Remark: Generated from `#/components/schemas/Attachment/state`.
            public var state: Components.Schemas.Attachment.StatePayload
            /// - Remark: Generated from `#/components/schemas/Attachment/mimeType`.
            public var mimeType: Swift.String
            /// - Remark: Generated from `#/components/schemas/Attachment/byteSize`.
            public var byteSize: Swift.Int64
            /// - Remark: Generated from `#/components/schemas/Attachment/failureReason`.
            public var failureReason: Swift.String?
            /// Creates a new `Attachment`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - draftId:
            ///   - position:
            ///   - source:
            ///   - state:
            ///   - mimeType:
            ///   - byteSize:
            ///   - failureReason:
            public init(
                id: Swift.String,
                draftId: Swift.String,
                position: Swift.Int,
                source: Components.Schemas.AttachmentSource,
                state: Components.Schemas.Attachment.StatePayload,
                mimeType: Swift.String,
                byteSize: Swift.Int64,
                failureReason: Swift.String? = nil
            ) {
                self.id = id
                self.draftId = draftId
                self.position = position
                self.source = source
                self.state = state
                self.mimeType = mimeType
                self.byteSize = byteSize
                self.failureReason = failureReason
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case draftId
                case position
                case source
                case state
                case mimeType
                case byteSize
                case failureReason
            }
        }
        /// Where the image came from. Only for diagnostics/UI; processing ignores it (spec 22).
        ///
        /// - Remark: Generated from `#/components/schemas/AttachmentSource`.
        @frozen public enum AttachmentSource: String, Codable, Hashable, Sendable, CaseIterable {
            case camera = "camera"
            case photoLibrary = "photoLibrary"
        }
        /// - Remark: Generated from `#/components/schemas/RegisterAttachmentRequest`.
        public struct RegisterAttachmentRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/RegisterAttachmentRequest/mimeType`.
            @frozen public enum MimeTypePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case imageJpeg = "image/jpeg"
                case imagePng = "image/png"
            }
            /// - Remark: Generated from `#/components/schemas/RegisterAttachmentRequest/mimeType`.
            public var mimeType: Components.Schemas.RegisterAttachmentRequest.MimeTypePayload
            /// - Remark: Generated from `#/components/schemas/RegisterAttachmentRequest/byteSize`.
            public var byteSize: Swift.Int64
            /// Lower-case hex SHA-256 of the bytes that will be uploaded.
            ///
            /// - Remark: Generated from `#/components/schemas/RegisterAttachmentRequest/sha256`.
            public var sha256: Swift.String
            /// - Remark: Generated from `#/components/schemas/RegisterAttachmentRequest/source`.
            public var source: Components.Schemas.AttachmentSource
            /// - Remark: Generated from `#/components/schemas/RegisterAttachmentRequest/width`.
            public var width: Swift.Int?
            /// - Remark: Generated from `#/components/schemas/RegisterAttachmentRequest/height`.
            public var height: Swift.Int?
            /// Creates a new `RegisterAttachmentRequest`.
            ///
            /// - Parameters:
            ///   - mimeType:
            ///   - byteSize:
            ///   - sha256: Lower-case hex SHA-256 of the bytes that will be uploaded.
            ///   - source:
            ///   - width:
            ///   - height:
            public init(
                mimeType: Components.Schemas.RegisterAttachmentRequest.MimeTypePayload,
                byteSize: Swift.Int64,
                sha256: Swift.String,
                source: Components.Schemas.AttachmentSource,
                width: Swift.Int? = nil,
                height: Swift.Int? = nil
            ) {
                self.mimeType = mimeType
                self.byteSize = byteSize
                self.sha256 = sha256
                self.source = source
                self.width = width
                self.height = height
            }
            public enum CodingKeys: String, CodingKey {
                case mimeType
                case byteSize
                case sha256
                case source
                case width
                case height
            }
        }
        /// - Remark: Generated from `#/components/schemas/SubmitDraftRequest`.
        public struct SubmitDraftRequest: Codable, Hashable, Sendable {
            /// Optional; with attachments it becomes the text of the same message.
            ///
            /// - Remark: Generated from `#/components/schemas/SubmitDraftRequest/text`.
            public var text: Swift.String?
            /// Creates a new `SubmitDraftRequest`.
            ///
            /// - Parameters:
            ///   - text: Optional; with attachments it becomes the text of the same message.
            public init(text: Swift.String? = nil) {
                self.text = text
            }
            public enum CodingKeys: String, CodingKey {
                case text
            }
        }
        /// - Remark: Generated from `#/components/schemas/AiRequest`.
        public struct AiRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/AiRequest/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/AiRequest/conversationId`.
            public var conversationId: Swift.String
            /// - Remark: Generated from `#/components/schemas/AiRequest/state`.
            @frozen public enum StatePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case waitingForAttachments = "waitingForAttachments"
                case blocked = "blocked"
                case queued = "queued"
                case processing = "processing"
                case completed = "completed"
                case failed = "failed"
                case cancelled = "cancelled"
            }
            /// - Remark: Generated from `#/components/schemas/AiRequest/state`.
            public var state: Components.Schemas.AiRequest.StatePayload
            /// Set in waitingForAttachments.
            ///
            /// - Remark: Generated from `#/components/schemas/AiRequest/uploadedAttachments`.
            public var uploadedAttachments: Swift.Int?
            /// Set in waitingForAttachments.
            ///
            /// - Remark: Generated from `#/components/schemas/AiRequest/totalAttachments`.
            public var totalAttachments: Swift.Int?
            /// Set in blocked.
            ///
            /// - Remark: Generated from `#/components/schemas/AiRequest/failedAttachments`.
            public var failedAttachments: Swift.Int?
            /// Set in completed.
            ///
            /// - Remark: Generated from `#/components/schemas/AiRequest/assistantMessageId`.
            public var assistantMessageId: Swift.String?
            /// Set in failed; safe to show to the user.
            ///
            /// - Remark: Generated from `#/components/schemas/AiRequest/failureReason`.
            public var failureReason: Swift.String?
            /// Creates a new `AiRequest`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - conversationId:
            ///   - state:
            ///   - uploadedAttachments: Set in waitingForAttachments.
            ///   - totalAttachments: Set in waitingForAttachments.
            ///   - failedAttachments: Set in blocked.
            ///   - assistantMessageId: Set in completed.
            ///   - failureReason: Set in failed; safe to show to the user.
            public init(
                id: Swift.String,
                conversationId: Swift.String,
                state: Components.Schemas.AiRequest.StatePayload,
                uploadedAttachments: Swift.Int? = nil,
                totalAttachments: Swift.Int? = nil,
                failedAttachments: Swift.Int? = nil,
                assistantMessageId: Swift.String? = nil,
                failureReason: Swift.String? = nil
            ) {
                self.id = id
                self.conversationId = conversationId
                self.state = state
                self.uploadedAttachments = uploadedAttachments
                self.totalAttachments = totalAttachments
                self.failedAttachments = failedAttachments
                self.assistantMessageId = assistantMessageId
                self.failureReason = failureReason
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case conversationId
                case state
                case uploadedAttachments
                case totalAttachments
                case failedAttachments
                case assistantMessageId
                case failureReason
            }
        }
        /// RFC 9457 problem details.
        ///
        /// - Remark: Generated from `#/components/schemas/Problem`.
        public struct Problem: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Problem/type`.
            public var _type: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Problem/title`.
            public var title: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Problem/status`.
            public var status: Swift.Int?
            /// - Remark: Generated from `#/components/schemas/Problem/detail`.
            public var detail: Swift.String?
            /// Stable machine-readable code, e.g. draft_already_submitted, empty_draft.
            ///
            /// - Remark: Generated from `#/components/schemas/Problem/code`.
            public var code: Swift.String?
            /// Creates a new `Problem`.
            ///
            /// - Parameters:
            ///   - _type:
            ///   - title:
            ///   - status:
            ///   - detail:
            ///   - code: Stable machine-readable code, e.g. draft_already_submitted, empty_draft.
            public init(
                _type: Swift.String? = nil,
                title: Swift.String? = nil,
                status: Swift.Int? = nil,
                detail: Swift.String? = nil,
                code: Swift.String? = nil
            ) {
                self._type = _type
                self.title = title
                self.status = status
                self.detail = detail
                self.code = code
            }
            public enum CodingKeys: String, CodingKey {
                case _type = "type"
                case title
                case status
                case detail
                case code
            }
        }
    }
}
