// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {
        /// - Remark: Generated from `#/components/parameters/ConversationId`.
        public typealias ConversationId = Swift.String
        /// - Remark: Generated from `#/components/parameters/DraftId`.
        public typealias DraftId = Swift.String
        /// Generated by the client; makes registration idempotent.
        ///
        /// - Remark: Generated from `#/components/parameters/AttachmentId`.
        public typealias AttachmentId = Swift.String
    }
}
